# config.yaml

worker:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: scipy tensorflow --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: scipy tensorflow --upgrade

    